package ITI.JETS.Entities;// default package
// Generated Jan 10, 2023, 5:21:41 PM by Hibernate Tools 6.0.0.Alpha3


import jakarta.persistence.*;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student"
    ,catalog="inheritance1"
)
public class Student extends Person  implements java.io.Serializable {


     private Integer id;
//     private String firstName;
//     private String lastName;
     private String department;

    public Student() {
    }

    public Student( String department) {
//       this.firstName = firstName;
//       this.lastName = lastName;
       this.department = department;
    }
   
     @Id @GeneratedValue(strategy=GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
//    @Column(name="first_name", nullable=false, length=50)
//    public String getFirstName() {
//        return this.firstName;
//    }
//
//    public void setFirstName(String firstName) {
//        this.firstName = firstName;
//    }
//
//
//    @Column(name="last_name", nullable=false, length=50)
//    public String getLastName() {
//        return this.lastName;
//    }
//
//    public void setLastName(String lastName) {
//        this.lastName = lastName;
//    }

    
    @Column(name="department", nullable=false, length=45)
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }




}


