package ITI.JETS.Entities2;// default package
// Generated Jan 10, 2023, 5:59:22 PM by Hibernate Tools 6.0.0.Alpha3


import jakarta.persistence.*;
/**
 * Person generated by hbm2java
 */


@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class Person2   implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;

    public Person2() {
    }

    public Person2(String firstName, String lastName) {
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
     @Id @GeneratedValue(strategy=GenerationType.TABLE, generator = "pr")
     @TableGenerator(table="mySeq", name = "pr")

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


