// default package
// Generated Jan 15, 2023, 9:06:09 PM by Hibernate Tools 6.0.0.Alpha3
package com.springData.orm.Entites;

import java.util.Date;
import javax.persistence.*;
/**
 * Workorderplace generated by hbm2java
 */
@Entity
@Table(name="workorderplace"
    ,catalog="jpaws"
)
public class Workorderplace  implements java.io.Serializable {


     private Long id;
     private Actionreq actionreq;
     private PartsWorkshop partsWorkshop;
     private Workorder workorder;
     private Date datePublished;
     private String status;
     private Date statusDate;
     private String description;
     private Date startDate;
     private String pnReqMaterials;
     private String reqMaterials;
     private String quant;
     private String user;
     private Date relStatusDate;
     private String des;
     private String eaeNoId;
     private String woNumber;
     private boolean ene;
     private boolean qa;

    public Workorderplace() {
    }

	
    public Workorderplace(PartsWorkshop partsWorkshop, Workorder workorder, Date datePublished, boolean ene, boolean qa) {
        this.partsWorkshop = partsWorkshop;
        this.workorder = workorder;
        this.datePublished = datePublished;
        this.ene = ene;
        this.qa = qa;
    }
    public Workorderplace(Actionreq actionreq, PartsWorkshop partsWorkshop, Workorder workorder, Date datePublished, String status, Date statusDate, String description, Date startDate, String pnReqMaterials, String reqMaterials, String quant, String user, Date relStatusDate, String des, String eaeNoId, String woNumber, boolean ene, boolean qa) {
       this.actionreq = actionreq;
       this.partsWorkshop = partsWorkshop;
       this.workorder = workorder;
       this.datePublished = datePublished;
       this.status = status;
       this.statusDate = statusDate;
       this.description = description;
       this.startDate = startDate;
       this.pnReqMaterials = pnReqMaterials;
       this.reqMaterials = reqMaterials;
       this.quant = quant;
       this.user = user;
       this.relStatusDate = relStatusDate;
       this.des = des;
       this.eaeNoId = eaeNoId;
       this.woNumber = woNumber;
       this.ene = ene;
       this.qa = qa;
    }
   
     @Id @GeneratedValue(strategy=GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="action_req_id")
    public Actionreq getActionreq() {
        return this.actionreq;
    }
    
    public void setActionreq(Actionreq actionreq) {
        this.actionreq = actionreq;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="workshop_name_id", nullable=false)
    public PartsWorkshop getPartsWorkshop() {
        return this.partsWorkshop;
    }
    
    public void setPartsWorkshop(PartsWorkshop partsWorkshop) {
        this.partsWorkshop = partsWorkshop;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tagno_id", nullable=false)
    public Workorder getWorkorder() {
        return this.workorder;
    }
    
    public void setWorkorder(Workorder workorder) {
        this.workorder = workorder;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_published", nullable=false, length=26)
    public Date getDatePublished() {
        return this.datePublished;
    }
    
    public void setDatePublished(Date datePublished) {
        this.datePublished = datePublished;
    }

    
    @Column(name="status", length=25)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="status_date", length=10)
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    
    @Column(name="description", length=255)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    
    @Column(name="pn_req_materials", length=255)
    public String getPnReqMaterials() {
        return this.pnReqMaterials;
    }
    
    public void setPnReqMaterials(String pnReqMaterials) {
        this.pnReqMaterials = pnReqMaterials;
    }

    
    @Column(name="req_materials", length=255)
    public String getReqMaterials() {
        return this.reqMaterials;
    }
    
    public void setReqMaterials(String reqMaterials) {
        this.reqMaterials = reqMaterials;
    }

    
    @Column(name="Quant", length=255)
    public String getQuant() {
        return this.quant;
    }
    
    public void setQuant(String quant) {
        this.quant = quant;
    }

    
    @Column(name="user", length=255)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rel_status_date", length=10)
    public Date getRelStatusDate() {
        return this.relStatusDate;
    }
    
    public void setRelStatusDate(Date relStatusDate) {
        this.relStatusDate = relStatusDate;
    }

    
    @Column(name="des", length=255)
    public String getDes() {
        return this.des;
    }
    
    public void setDes(String des) {
        this.des = des;
    }

    
    @Column(name="eae_no_id", length=255)
    public String getEaeNoId() {
        return this.eaeNoId;
    }
    
    public void setEaeNoId(String eaeNoId) {
        this.eaeNoId = eaeNoId;
    }

    
    @Column(name="wo_number", length=25)
    public String getWoNumber() {
        return this.woNumber;
    }
    
    public void setWoNumber(String woNumber) {
        this.woNumber = woNumber;
    }

    
    @Column(name="ENE", nullable=false)
    public boolean isEne() {
        return this.ene;
    }
    
    public void setEne(boolean ene) {
        this.ene = ene;
    }

    
    @Column(name="QA", nullable=false)
    public boolean isQa() {
        return this.qa;
    }
    
    public void setQa(boolean qa) {
        this.qa = qa;
    }




}


