package ITI.JETS.Entities;// default package
// Generated Jan 7, 2023, 5:13:16 PM by Hibernate Tools 6.1.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="biddingschema"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String address;
     private String phone;
     private String mobile;
     private Date dateOfBirth;
     private Date registrationDate;
     private String userName;
     private String password;
     private String fullName;
     private Set<Buyer> buyers = new HashSet<Buyer>(0);
     private Seller seller;

    public User() {
    }

	
    public User(String email, String address, Date registrationDate, String userName, String password) {
        this.email = email;
        this.address = address;
        this.registrationDate = registrationDate;
        this.userName = userName;
        this.password = password;
    }
    public User(String email, String address, String phone, String mobile, Date dateOfBirth, Date registrationDate, String userName, String password, String fullName, Set<Buyer> buyers, Seller seller) {
       this.email = email;
       this.address = address;
       this.phone = phone;
       this.mobile = mobile;
       this.dateOfBirth = dateOfBirth;
       this.registrationDate = registrationDate;
       this.userName = userName;
       this.password = password;
       this.fullName = fullName;
       this.buyers = buyers;
       this.seller = seller;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="address", nullable=false, length=150)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="mobile", length=45)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_birth", length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="registration_date", nullable=false, length=10)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    
    @Column(name="user_name", nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="full_name", length=100)
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Buyer> getBuyers() {
        return this.buyers;
    }
    
    public void setBuyers(Set<Buyer> buyers) {
        this.buyers = buyers;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="user")
    public Seller getSeller() {
        return this.seller;
    }
    
    public void setSeller(Seller seller) {
        this.seller = seller;
    }




}


