// default package
// Generated Jan 15, 2023, 9:06:09 PM by Hibernate Tools 6.0.0.Alpha3
package com.Entities;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
/**
 * Aircraftmodel generated by hbm2java
 */
@Entity
@Table(name="aircraftmodel"
    ,catalog="jpaws"
)
public class Aircraftmodel  implements java.io.Serializable {


     private String acmodel;
     private Date datePublished;
     private String name;
     private Set<Capabilitylist> capabilitylists = new HashSet<Capabilitylist>(0);
     private Set<Aircrafttype> aircrafttypes = new HashSet<Aircrafttype>(0);

    public Aircraftmodel() {
    }

	
    public Aircraftmodel(String acmodel, Date datePublished, String name) {
        this.acmodel = acmodel;
        this.datePublished = datePublished;
        this.name = name;
    }
    public Aircraftmodel(String acmodel, Date datePublished, String name, Set<Capabilitylist> capabilitylists, Set<Aircrafttype> aircrafttypes) {
       this.acmodel = acmodel;
       this.datePublished = datePublished;
       this.name = name;
       this.capabilitylists = capabilitylists;
       this.aircrafttypes = aircrafttypes;
    }
   
     @Id 

    
    @Column(name="acmodel", unique=true, nullable=false, length=55)
    public String getAcmodel() {
        return this.acmodel;
    }
    
    public void setAcmodel(String acmodel) {
        this.acmodel = acmodel;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_published", nullable=false, length=26)
    public Date getDatePublished() {
        return this.datePublished;
    }
    
    public void setDatePublished(Date datePublished) {
        this.datePublished = datePublished;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aircraftmodel")
    public Set<Capabilitylist> getCapabilitylists() {
        return this.capabilitylists;
    }
    
    public void setCapabilitylists(Set<Capabilitylist> capabilitylists) {
        this.capabilitylists = capabilitylists;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="aircraftmodel")
    public Set<Aircrafttype> getAircrafttypes() {
        return this.aircrafttypes;
    }
    
    public void setAircrafttypes(Set<Aircrafttype> aircrafttypes) {
        this.aircrafttypes = aircrafttypes;
    }




}


