package ITI.JETS.Entities1;// default package
// Generated Jan 10, 2023, 5:21:41 PM by Hibernate Tools 6.0.0.Alpha3



import jakarta.persistence.*;


/**
 * Person generated by hbm2java
 */
//@Entity
@Table(name="person"
   ,catalog="inheritance1"
)
@MappedSuperclass
public abstract class Person1  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;

    public Person1() {
    }

    public Person1(String firstName, String lastName) {
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
     @Id @GeneratedValue(strategy= GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="first_name", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


