package ITI.JETS.Entities1;// default package
// Generated Jan 10, 2023, 5:21:41 PM by Hibernate Tools 6.0.0.Alpha3


import java.util.Date;
import jakarta.persistence.*;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name="teacher"
    ,catalog="inheritance1"
)
public class Teacher1 extends Person1  implements java.io.Serializable {


     private Integer id;
     private Date hireDate;

    public Teacher1() {
    }

    public Teacher1( Date hireDate) {

       this.hireDate = hireDate;
    }
   
     @Id @GeneratedValue(strategy=GenerationType.IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
//    @Column(name="first_name", nullable=false, length=50)
//    public String getFirstName() {
//        return this.firstName;
//    }
//
//    public void setFirstName(String firstName) {
//        this.firstName = firstName;
//    }
//
//
//    @Column(name="last_name", nullable=false, length=50)
//    public String getLastName() {
//        return this.lastName;
//    }
//
//    public void setLastName(String lastName) {
//        this.lastName = lastName;
//    }

    @Temporal(TemporalType.DATE)
    @Column(name="hire_date", nullable=false, length=10)
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }




}


