package ITI.JETS.Entities4;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "inheritance4")
public class Student4 extends Person4 {

    private String department;

    public Student4() {
    }

    public Student4(String department) {
        this.department = department;
    }
    public Student4(String firstName, String lastName, String department, String personType) {
        super(firstName, lastName, personType);
        this.department = department;
    }

    @Column(name = "department", nullable = false, length = 45)
    public String getDepartment() {
        return this.department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

}
