// default package
// Generated Jan 15, 2023, 9:06:09 PM by Hibernate Tools 6.0.0.Alpha3
package com.Entities;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
/**
 * Typeofservices generated by hbm2java
 */
@Entity
@Table(name="typeofservices"
    ,catalog="jpaws"
)
public class Typeofservices  implements java.io.Serializable {


     private String code;
     private Date datePublished;
     private String name;
     private Set<Workorder> workorders = new HashSet<Workorder>(0);

    public Typeofservices() {
    }

	
    public Typeofservices(String code, Date datePublished, String name) {
        this.code = code;
        this.datePublished = datePublished;
        this.name = name;
    }
    public Typeofservices(String code, Date datePublished, String name, Set<Workorder> workorders) {
       this.code = code;
       this.datePublished = datePublished;
       this.name = name;
       this.workorders = workorders;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_published", nullable=false, length=26)
    public Date getDatePublished() {
        return this.datePublished;
    }
    
    public void setDatePublished(Date datePublished) {
        this.datePublished = datePublished;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typeofservices")
    public Set<Workorder> getWorkorders() {
        return this.workorders;
    }
    
    public void setWorkorders(Set<Workorder> workorders) {
        this.workorders = workorders;
    }




}


