// default package
// Generated Jan 15, 2023, 9:06:09 PM by Hibernate Tools 6.0.0.Alpha3
package com.Entities;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;
/**
 * Workorder generated by hbm2java
 */
@Entity
@Table(name="workorder"
    ,catalog="jpaws"
)
public class Workorder  implements java.io.Serializable {


     private String tagno;
     private Aircrafttype aircrafttype;
     private Typeofservices typeofservices;
     private Owner owner;
     private Date datePublished;
     private String refNo;
     private String ordStatus;
     private Date receivedDate;
     private Date exitDate;
     private String acModelId;
     private String pn;
     private String name;
     private String SN;
     private String user;
     private String peruority;
     private Set<Workorderplace> workorderplaces = new HashSet<Workorderplace>(0);

    public Workorder() {
    }

	
    public Workorder(String tagno, Owner owner, Date datePublished, String ordStatus, String acModelId, String pn, String name) {
        this.tagno = tagno;
        this.owner = owner;
        this.datePublished = datePublished;
        this.ordStatus = ordStatus;
        this.acModelId = acModelId;
        this.pn = pn;
        this.name = name;
    }
    public Workorder(String tagno, Aircrafttype aircrafttype, Typeofservices typeofservices, Owner owner, Date datePublished, String refNo, String ordStatus, Date receivedDate, Date exitDate, String acModelId, String pn, String name, String SN, String user, String peruority, Set<Workorderplace> workorderplaces) {
       this.tagno = tagno;
       this.aircrafttype = aircrafttype;
       this.typeofservices = typeofservices;
       this.owner = owner;
       this.datePublished = datePublished;
       this.refNo = refNo;
       this.ordStatus = ordStatus;
       this.receivedDate = receivedDate;
       this.exitDate = exitDate;
       this.acModelId = acModelId;
       this.pn = pn;
       this.name = name;
       this.SN = SN;
       this.user = user;
       this.peruority = peruority;
       this.workorderplaces = workorderplaces;
    }
   
     @Id 

    
    @Column(name="tagno", unique=true, nullable=false, length=10)
    public String getTagno() {
        return this.tagno;
    }
    
    public void setTagno(String tagno) {
        this.tagno = tagno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ac_type_id")
    public Aircrafttype getAircrafttype() {
        return this.aircrafttype;
    }
    
    public void setAircrafttype(Aircrafttype aircrafttype) {
        this.aircrafttype = aircrafttype;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_of_services_id")
    public Typeofservices getTypeofservices() {
        return this.typeofservices;
    }
    
    public void setTypeofservices(Typeofservices typeofservices) {
        this.typeofservices = typeofservices;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="owner_name_id", nullable=false)
    public Owner getOwner() {
        return this.owner;
    }
    
    public void setOwner(Owner owner) {
        this.owner = owner;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_published", nullable=false, length=26)
    public Date getDatePublished() {
        return this.datePublished;
    }
    
    public void setDatePublished(Date datePublished) {
        this.datePublished = datePublished;
    }

    
    @Column(name="ref_no", length=50)
    public String getRefNo() {
        return this.refNo;
    }
    
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }

    
    @Column(name="ord_status", nullable=false, length=25)
    public String getOrdStatus() {
        return this.ordStatus;
    }
    
    public void setOrdStatus(String ordStatus) {
        this.ordStatus = ordStatus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="received_date", length=10)
    public Date getReceivedDate() {
        return this.receivedDate;
    }
    
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="exit_date", length=10)
    public Date getExitDate() {
        return this.exitDate;
    }
    
    public void setExitDate(Date exitDate) {
        this.exitDate = exitDate;
    }

    
    @Column(name="ac_model_id", nullable=false, length=55)
    public String getAcModelId() {
        return this.acModelId;
    }
    
    public void setAcModelId(String acModelId) {
        this.acModelId = acModelId;
    }

    
    @Column(name="pn", nullable=false, length=255)
    public String getPn() {
        return this.pn;
    }
    
    public void setPn(String pn) {
        this.pn = pn;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="S_N", length=255)
    public String getSN() {
        return this.SN;
    }
    
    public void setSN(String SN) {
        this.SN = SN;
    }

    
    @Column(name="user", length=255)
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    
    @Column(name="peruority", length=50)
    public String getPeruority() {
        return this.peruority;
    }
    
    public void setPeruority(String peruority) {
        this.peruority = peruority;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="workorder")
    public Set<Workorderplace> getWorkorderplaces() {
        return this.workorderplaces;
    }
    
    public void setWorkorderplaces(Set<Workorderplace> workorderplaces) {
        this.workorderplaces = workorderplaces;
    }




}


